{% set development = development|default(false) %}
version: '3'

services:
  {{ Values.serviceName }}:
    image: rediscommander/redis-commander:{{ Values.image.tag }}
    restart: always
    environment:
      {% if Values.redis.usePassword %}
      - REDIS_HOSTS=main:{{ Values.redis.host }}:{{ Values.redis.port }}:{{ Values.redis.db }}:{{ Values.redis.password }}
      {% else %}
      - REDIS_HOSTS=main:{{ Values.redis.host }}:{{ Values.redis.port }}:{{ Values.redis.db }}
      {% endif %}

    ports:
      - {{ Values.service.port }}:{{ Values.service.targetPort }}
